#!/bin/bash

cd ~/App
docker rmi ncsu-app
docker rmi localhost:5000/ncsu:latest
docker build -t ncsu-app .
#docker run -p 50100:8080 -d --name app ncsu-app
docker tag -f ncsu-app localhost:5000/ncsu:latest
docker push localhost:5000/ncsu:latest
